name: linting

on:
 push:
 pull_request:
   types: [opened, reopened]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install .[dev]
      - name: Check style against standards using prospector
        run: prospector --zero-exit -o grouped -o pylint:pylint-report.txt
